[workspace]
resolver = "2"
members = ["crates/asb-core", "crates/asb-switch", "src-tauri"]

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
thiserror = "2"
