//! Generated, credential-free configuration evidence for the public website.
//!
//! The website never recreates client configuration text. This module uses the
//! same pure adapters as the desktop application, then emits a committed static
//! TypeScript artifact for Vercel to serve.

use crate::adapter;
use crate::contracts::{
    AppKind, CommonSettingValue, CommonSettings, ConfigValue, ProviderProfile, RouteMode,
    SwitchPlan,
};
use crate::ownership::{
    default_common_settings, official_setting_directory, owner_for, setting_spec, ChoiceControl,
    OfficialSettingDisposition, SettingControl, SettingOwner,
};
use crate::redact::REDACTED;
use serde::Serialize;

const DEMO_API_KEY: &str = "website-generated-demo-key";
const BEDROCK_ENDPOINT: &str = "https://bedrock-runtime.us-east-1.amazonaws.com/v1";

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WebsiteAssembly {
    codex: WebsiteAssemblyClient,
    claude: WebsiteAssemblyClient,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WebsiteAssemblyClient {
    id: &'static str,
    tone: &'static str,
    client: &'static str,
    provider: String,
    common_fields: Vec<WebsiteAssemblyField>,
    provider_fields: Vec<WebsiteAssemblyField>,
    file_name: &'static str,
    file_path: &'static str,
    code_lines: Vec<String>,
    preserved_paths: Vec<String>,
}

#[derive(Serialize)]
struct WebsiteAssemblyField {
    key: String,
    value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    control: Option<&'static str>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    options: Vec<String>,
}

/// Renders the sole website configuration-evidence artifact.
pub fn typescript() -> String {
    let assembly = WebsiteAssembly {
        codex: client(AppKind::Codex),
        claude: client(AppKind::Claude),
    };
    let json = serde_json::to_string_pretty(&assembly).expect("website assembly serializes");

    format!(
        "// This file is generated by `cargo run -p asb-core --bin generate-website-assembly`.\n// Do not edit it by hand; the desktop adapters own these rendered lines.\n\nexport const configurationAssembly = {json} as const;\n\nexport type ConfigurationAssemblyClientId = keyof typeof configurationAssembly;\nexport type ConfigurationAssemblyClient = (typeof configurationAssembly)[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyCommonField = {{\n  [ClientId in ConfigurationAssemblyClientId]: (typeof configurationAssembly)[ClientId][\"commonFields\"][number];\n}}[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyProviderField = {{\n  [ClientId in ConfigurationAssemblyClientId]: (typeof configurationAssembly)[ClientId][\"providerFields\"][number];\n}}[ConfigurationAssemblyClientId];\nexport type ConfigurationAssemblyFieldKey =\n  | ConfigurationAssemblyCommonField[\"key\"]\n  | ConfigurationAssemblyProviderField[\"key\"];\nexport type ConfigurationAssemblyControlValue =\n  ConfigurationAssemblyCommonField[\"options\"][number];\n"
    )
}

fn client(app: AppKind) -> WebsiteAssemblyClient {
    let plan = plan(app);
    let current = match app {
        AppKind::Codex => "",
        AppKind::Claude => "{}",
    };
    let candidate = adapter::render(current, &plan).expect("website demonstration plan is valid");
    let public_candidate = candidate.replace(DEMO_API_KEY, REDACTED);
    adapter::validate_syntax(app, &public_candidate)
        .expect("redacted website demonstration remains valid client configuration");
    let fields = adapter::owned_diff(app, &public_candidate, current)
        .expect("website demonstration candidate has an owned diff")
        .into_iter()
        .filter_map(|change| {
            change.after.map(|value| {
                let (control, options) = common_control(app, &change.key);
                WebsiteAssemblyField {
                    key: change.key,
                    value,
                    control,
                    options,
                }
            })
        });
    let (common_fields, provider_fields): (Vec<_>, Vec<_>) =
        fields.partition(|field| owner_for(app, &field.key) == SettingOwner::Common);

    let (id, tone, client, file_name) = match app {
        AppKind::Codex => ("codex", "codex", "Codex", "config.toml"),
        AppKind::Claude => ("claude", "claude", "Claude Code", "settings.json"),
    };

    WebsiteAssemblyClient {
        id,
        tone,
        client,
        provider: plan.profile.name,
        common_fields,
        provider_fields,
        file_name,
        file_path: app.config_label(),
        code_lines: public_candidate.lines().map(str::to_owned).collect(),
        preserved_paths: official_setting_directory(app)
            .into_iter()
            .filter(|entry| entry.disposition == OfficialSettingDisposition::PreserveOnly)
            .take(2)
            .map(|entry| entry.path.to_owned())
            .collect(),
    }
}

/// The website consumes the desktop ownership catalog's control metadata; it
/// never infers a visual control from a rendered configuration value.
fn common_control(app: AppKind, key: &str) -> (Option<&'static str>, Vec<String>) {
    let Some(spec) = setting_spec(app, key) else {
        return (None, vec![]);
    };
    if spec.owner != SettingOwner::Common {
        return (None, vec![]);
    }

    match spec.control {
        SettingControl::Toggle => (
            Some("toggle"),
            ["automatic", "true", "false"]
                .into_iter()
                .map(str::to_owned)
                .collect(),
        ),
        SettingControl::Choice { presentation } => (
            Some(match presentation {
                ChoiceControl::Slider => "slider",
                ChoiceControl::Segment => "segment",
            }),
            std::iter::once("automatic".to_owned())
                .chain(
                    spec.allowed_values
                        .iter()
                        .map(|option| option.value.to_owned()),
                )
                .collect(),
        ),
        SettingControl::None => unreachable!("common settings always have controls"),
    }
}

fn plan(app: AppKind) -> SwitchPlan {
    let mut common = default_common_settings(app);
    match app {
        AppKind::Codex => {
            explicit(
                &mut common,
                "model_reasoning_effort",
                ConfigValue::Str("high".into()),
            );
            explicit(&mut common, "hide_agent_reasoning", ConfigValue::Bool(true));
        }
        AppKind::Claude => {
            explicit(&mut common, "effortLevel", ConfigValue::Str("high".into()));
            explicit(&mut common, "autoCompactEnabled", ConfigValue::Bool(true));
        }
    }

    let (model, id) = match app {
        AppKind::Codex => ("GPT-6 Astra", "website-codex"),
        AppKind::Claude => ("Claude Opus 5.1", "website-claude"),
    };
    SwitchPlan {
        profile: ProviderProfile {
            id: id.into(),
            app,
            route_mode: RouteMode::Custom,
            name: "Amazon Bedrock".into(),
            model: Some(model.into()),
            base_url: Some(BEDROCK_ENDPOINT.into()),
            api_key: DEMO_API_KEY.into(),
            model_options: None,
            notes: None,
            website_url: None,
            usage_query: None,
        },
        common,
    }
}

fn explicit(common: &mut CommonSettings, key: &str, value: ConfigValue) {
    common
        .settings
        .insert(key.into(), CommonSettingValue::Explicit { value });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_website_assembly_matches_the_committed_artifact() {
        let generated = typescript();
        let committed = include_str!("../../../website/src/generated/configuration-assembly.ts");
        assert_eq!(committed, generated, "run the website assembly generator");
    }

    #[test]
    fn website_assembly_is_rendered_by_the_adapters_and_redacts_credentials() {
        let generated = typescript();

        assert!(generated.contains("model_provider"));
        assert!(generated.contains("ANTHROPIC_AUTH_TOKEN"));
        assert!(generated.contains(REDACTED));
        assert!(generated.contains("\"control\": \"toggle\""));
        assert!(generated.contains("\"control\": \"slider\""));
        assert!(generated.contains("\"preservedPaths\""));
        assert!(generated.contains("mcp_servers.<id>"));
        assert!(generated.contains("\"permissions\""));
        assert!(!generated.contains(DEMO_API_KEY));
    }
}
