//! Application-runtime event logging.
//!
//! This module owns the only runtime-log contract. It emits closed, non-secret
//! events through the application logger and reads back only this application's
//! rotated JSON-line files for the renderer. It never receives configuration
//! text, credentials, paths, request bodies, or error messages.

use chrono::DateTime;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU8, Ordering};
use tauri::{AppHandle, Manager};

const LOG_FILE_STEM: &str = "agent-switchboard";
const LOG_TARGET: &str = "agent-switchboard.runtime";
const MAX_VISIBLE_ENTRIES: usize = 500;

/// Persisted threshold for application runtime-event recording.
///
/// `Silent` means that no new events are written. It is deliberately not a
/// severity that can appear in a persisted event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RuntimeLogLevel {
    Debug,
    Info,
    Warn,
    Error,
    Silent,
}

impl RuntimeLogLevel {
    const fn as_code(self) -> u8 {
        match self {
            Self::Debug => 0,
            Self::Info => 1,
            Self::Warn => 2,
            Self::Error => 3,
            Self::Silent => 4,
        }
    }

    fn allows(self, severity: RuntimeLogSeverity) -> bool {
        match self {
            Self::Debug => true,
            Self::Info => severity != RuntimeLogSeverity::Debug,
            Self::Warn => matches!(
                severity,
                RuntimeLogSeverity::Warn | RuntimeLogSeverity::Error
            ),
            Self::Error => severity == RuntimeLogSeverity::Error,
            Self::Silent => false,
        }
    }
}

/// Severity of one persisted application runtime event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RuntimeLogSeverity {
    Debug,
    Info,
    Warn,
    Error,
}

static ACTIVE_LOG_LEVEL: AtomicU8 = AtomicU8::new(RuntimeLogLevel::Info.as_code());

/// A closed set of user-relevant application actions. Values deliberately do
/// not include a profile name, a configuration path, or any other user data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RuntimeLogAction {
    AppStarted,
    AppSettingsSaved,
    ProfileStoreReset,
    ProfileCreated,
    ProfileUpdated,
    ProfileDeleted,
    ProfilesReordered,
    ProfileImported,
    CommonSettingsSaved,
    CommonSettingsApplied,
    GlobalPromptDocumentSaved,
    ConfigurationSwitched,
    BackupRestored,
    SwitchUndone,
    StaleLockRecovered,
    CloudBackupSettingsSaved,
    CloudBackupUploaded,
    CloudBackupRestored,
    SessionResumed,
    CcSwitchProfilesImported,
}

/// One persisted, renderer-safe runtime event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeLogEntry {
    /// RFC 3339 UTC timestamp generated by this module.
    pub at: String,
    pub level: RuntimeLogSeverity,
    pub action: RuntimeLogAction,
    /// Stable typed command error code, present only for failed actions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
}

/// Registers the app-owned runtime logger before command setup. The same
/// bounded files are used by the diagnostic Log tab and never by the renderer
/// directly.
pub fn plugin<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    use tauri_plugin_log::{RotationStrategy, Target, TargetKind, TimezoneStrategy};

    tauri_plugin_log::Builder::new()
        .timezone_strategy(TimezoneStrategy::UseLocal)
        // Runtime events are already serialized JSON lines. Keeping the
        // message unchanged makes parsing independent from display formats.
        .clear_format()
        // `record` owns the runtime-configurable threshold. Keep the plugin
        // open through Debug so an enabled Debug event reaches its targets.
        .level(log::LevelFilter::Debug)
        // Do not capture third-party output: it can contain caller-owned
        // request/configuration details that are outside this log contract.
        .filter(|metadata| metadata.target() == LOG_TARGET)
        .targets([
            Target::new(TargetKind::Stdout),
            Target::new(TargetKind::LogDir {
                file_name: Some(LOG_FILE_STEM.to_string()),
            }),
        ])
        // Keep the current file plus four size-rotated archives, matching the
        // bounded diagnostic-file behavior used by the public CC Switch code.
        .rotation_strategy(RotationStrategy::KeepSome(4))
        .max_file_size(20 * 1024 * 1024)
        .build()
}

pub fn record_started() {
    record(RuntimeLogSeverity::Info, RuntimeLogAction::AppStarted, None);
}

pub fn record_success(action: RuntimeLogAction) {
    record(RuntimeLogSeverity::Info, action, None);
}

pub fn record_failure(action: RuntimeLogAction, error_code: &str) {
    record(
        RuntimeLogSeverity::Error,
        action,
        Some(error_code.to_string()),
    );
}

/// Applies a successfully persisted application setting to future writes.
pub fn set_level(level: RuntimeLogLevel) {
    ACTIVE_LOG_LEVEL.store(level.as_code(), Ordering::Relaxed);
}

fn active_level() -> RuntimeLogLevel {
    match ACTIVE_LOG_LEVEL.load(Ordering::Relaxed) {
        0 => RuntimeLogLevel::Debug,
        1 => RuntimeLogLevel::Info,
        2 => RuntimeLogLevel::Warn,
        3 => RuntimeLogLevel::Error,
        4 => RuntimeLogLevel::Silent,
        value => unreachable!("runtime log level cache contains invalid value {value}"),
    }
}

fn record(level: RuntimeLogSeverity, action: RuntimeLogAction, error_code: Option<String>) {
    if !active_level().allows(level) {
        return;
    }

    let entry = RuntimeLogEntry {
        at: chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
        level,
        action,
        error_code,
    };
    let Ok(payload) = serde_json::to_string(&entry) else {
        return;
    };

    match entry.level {
        RuntimeLogSeverity::Debug => log::debug!(target: LOG_TARGET, "{payload}"),
        RuntimeLogSeverity::Info => log::info!(target: LOG_TARGET, "{payload}"),
        RuntimeLogSeverity::Warn => log::warn!(target: LOG_TARGET, "{payload}"),
        RuntimeLogSeverity::Error => log::error!(target: LOG_TARGET, "{payload}"),
    }
}

/// Reads only this application's current and rotated runtime-event files.
/// An empty log directory is a normal first-run state.
pub fn list(app: &AppHandle) -> Result<Vec<RuntimeLogEntry>, String> {
    let directory = log_directory(app)?;
    list_from_dir(&directory)
}

/// Resolves the only directory that contains this application's runtime logs.
/// The path remains backend-owned and is never returned to the renderer.
pub fn log_directory(app: &AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_log_dir()
        .map_err(|_| "无法定位应用日志目录".to_string())
}

fn list_from_dir(directory: &Path) -> Result<Vec<RuntimeLogEntry>, String> {
    let files = match fs::read_dir(directory) {
        Ok(files) => files,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(vec![]),
        Err(_) => return Err("应用日志目录不可读".to_string()),
    };
    let mut entries = Vec::new();

    for file in files {
        let file = file.map_err(|_| "应用日志目录不可读".to_string())?;
        let path = file.path();
        if !file
            .file_type()
            .map_err(|_| "应用日志目录不可读".to_string())?
            .is_file()
            || !is_runtime_log_file(&path)
        {
            continue;
        }
        let text = fs::read_to_string(&path).map_err(|_| "应用日志不可读".to_string())?;
        for line in text.lines() {
            let Ok(entry) = serde_json::from_str::<RuntimeLogEntry>(line) else {
                // The current file can be read while an incomplete final line
                // is still being flushed. Old or foreign lines never become UI
                // data merely because they share the directory.
                continue;
            };
            if entry.is_valid() {
                entries.push(entry);
            }
        }
    }

    entries.sort_by(|left, right| right.at.cmp(&left.at));
    entries.truncate(MAX_VISIBLE_ENTRIES);
    Ok(entries)
}

fn is_runtime_log_file(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    name == format!("{LOG_FILE_STEM}.log")
        || (name.starts_with(&format!("{LOG_FILE_STEM}_")) && name.ends_with(".log"))
}

impl RuntimeLogEntry {
    fn is_valid(&self) -> bool {
        if !self.at.ends_with('Z') || DateTime::parse_from_rfc3339(&self.at).is_err() {
            return false;
        }
        match self.level {
            RuntimeLogSeverity::Debug | RuntimeLogSeverity::Info | RuntimeLogSeverity::Warn => {
                self.error_code.is_none()
            }
            RuntimeLogSeverity::Error => self.error_code.as_deref().is_some_and(is_error_code),
        }
    }
}

fn is_error_code(code: &str) -> bool {
    !code.is_empty()
        && code.len() <= 96
        && code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(at: &str, level: RuntimeLogSeverity, action: RuntimeLogAction) -> RuntimeLogEntry {
        RuntimeLogEntry {
            at: at.to_string(),
            level,
            action,
            error_code: (level == RuntimeLogSeverity::Error)
                .then(|| "operation-failed".to_string()),
        }
    }

    #[test]
    fn log_levels_apply_standard_thresholds() {
        assert!(RuntimeLogLevel::Debug.allows(RuntimeLogSeverity::Debug));
        assert!(RuntimeLogLevel::Debug.allows(RuntimeLogSeverity::Info));
        assert!(RuntimeLogLevel::Debug.allows(RuntimeLogSeverity::Warn));
        assert!(RuntimeLogLevel::Debug.allows(RuntimeLogSeverity::Error));

        assert!(!RuntimeLogLevel::Info.allows(RuntimeLogSeverity::Debug));
        assert!(RuntimeLogLevel::Info.allows(RuntimeLogSeverity::Info));
        assert!(RuntimeLogLevel::Info.allows(RuntimeLogSeverity::Warn));
        assert!(RuntimeLogLevel::Info.allows(RuntimeLogSeverity::Error));

        assert!(!RuntimeLogLevel::Warn.allows(RuntimeLogSeverity::Debug));
        assert!(!RuntimeLogLevel::Warn.allows(RuntimeLogSeverity::Info));
        assert!(RuntimeLogLevel::Warn.allows(RuntimeLogSeverity::Warn));
        assert!(RuntimeLogLevel::Warn.allows(RuntimeLogSeverity::Error));

        assert!(!RuntimeLogLevel::Error.allows(RuntimeLogSeverity::Debug));
        assert!(!RuntimeLogLevel::Error.allows(RuntimeLogSeverity::Info));
        assert!(!RuntimeLogLevel::Error.allows(RuntimeLogSeverity::Warn));
        assert!(RuntimeLogLevel::Error.allows(RuntimeLogSeverity::Error));

        assert!(!RuntimeLogLevel::Silent.allows(RuntimeLogSeverity::Debug));
        assert!(!RuntimeLogLevel::Silent.allows(RuntimeLogSeverity::Info));
        assert!(!RuntimeLogLevel::Silent.allows(RuntimeLogSeverity::Warn));
        assert!(!RuntimeLogLevel::Silent.allows(RuntimeLogSeverity::Error));
    }

    #[test]
    fn reads_current_and_rotated_files_in_reverse_time_order() {
        let directory = tempfile::tempdir().expect("temporary log directory");
        let older = entry(
            "2026-08-31T01:02:03.000Z",
            RuntimeLogSeverity::Info,
            RuntimeLogAction::AppStarted,
        );
        let newer = entry(
            "2026-08-31T02:03:04.000Z",
            RuntimeLogSeverity::Error,
            RuntimeLogAction::ConfigurationSwitched,
        );
        fs::write(
            directory
                .path()
                .join("agent-switchboard_2026-08-31_01-00-00.log"),
            serde_json::to_string(&older).expect("serialize older"),
        )
        .expect("write archived log");
        fs::write(
            directory.path().join("agent-switchboard.log"),
            serde_json::to_string(&newer).expect("serialize newer"),
        )
        .expect("write current log");

        let entries = list_from_dir(directory.path()).expect("read logs");
        assert_eq!(entries, vec![newer, older]);
    }

    #[test]
    fn reads_all_event_severities_except_silent() {
        let directory = tempfile::tempdir().expect("temporary log directory");
        let debug = entry(
            "2026-08-31T01:02:03.000Z",
            RuntimeLogSeverity::Debug,
            RuntimeLogAction::AppStarted,
        );
        let warn = entry(
            "2026-08-31T02:03:04.000Z",
            RuntimeLogSeverity::Warn,
            RuntimeLogAction::ProfileStoreReset,
        );
        fs::write(
            directory.path().join("agent-switchboard.log"),
            format!(
                "{}\n{}\n{{\"at\":\"2026-08-31T03:04:05.000Z\",\"level\":\"silent\",\"action\":\"appStarted\"}}",
                serde_json::to_string(&debug).expect("serialize debug"),
                serde_json::to_string(&warn).expect("serialize warn"),
            ),
        )
        .expect("write log entries");

        let entries = list_from_dir(directory.path()).expect("read logs");
        assert_eq!(entries, vec![warn, debug]);
    }

    #[test]
    fn ignores_malformed_and_non_contract_log_lines() {
        let directory = tempfile::tempdir().expect("temporary log directory");
        fs::write(
            directory.path().join("agent-switchboard.log"),
            concat!(
                "not json\n",
                "{\"at\":\"2026-08-31T01:02:03.000Z\",\"level\":\"info\",\"action\":\"appStarted\",\"message\":\"sk-secret\"}\n",
                "{\"at\":\"bad-time\",\"level\":\"error\",\"action\":\"appStarted\",\"errorCode\":\"operation-failed\"}\n"
            ),
        )
        .expect("write malformed lines");

        assert_eq!(list_from_dir(directory.path()).expect("read logs"), vec![]);
    }

    #[test]
    fn retains_only_the_newest_display_entries() {
        let directory = tempfile::tempdir().expect("temporary log directory");
        let path = directory.path().join("agent-switchboard.log");
        let lines = (0..=MAX_VISIBLE_ENTRIES)
            .map(|index| {
                serde_json::to_string(&entry(
                    &format!(
                        "2026-08-31T00:{:02}:{:02}.000Z",
                        (index / 60) % 60,
                        index % 60
                    ),
                    RuntimeLogSeverity::Info,
                    RuntimeLogAction::ProfileCreated,
                ))
                .expect("serialize entry")
            })
            .collect::<Vec<_>>()
            .join("\n");
        fs::write(path, lines).expect("write log entries");

        let entries = list_from_dir(directory.path()).expect("read logs");
        assert_eq!(entries.len(), MAX_VISIBLE_ENTRIES);
        assert_eq!(entries[0].at, "2026-08-31T00:08:20.000Z");
        assert_eq!(
            entries.last().map(|entry| entry.at.as_str()),
            Some("2026-08-31T00:00:01.000Z")
        );
    }
}
